[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM9
monitor_port = COM9
lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    bblanchon/ArduinoJson @ ^7.0.4
    arduino-libraries/NTPClient @ ^3.2.1